name: test for conda
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches:
      - dev
    paths:
      - 'nextflow.config'
  pull_request:
  release:
    types: [published]

jobs:
  test:
    name: Run workflow tests for conda
    # Only run on push if this is the dev branch (merged PRs)
    if: ${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'jianhong/chipseq') }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    env:
      NXF_VER: ${{ matrix.nxf_ver }}
      NXF_ANSI_LOG: false
    strategy:
      max-parallel: 6
      matrix:
        # Nextflow versions: check pipeline minimum and current latest
        nxf_ver: ['20.07.1', '']
        os: ["ubuntu-latest"]
        python-version: ["3.7"]
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults,bioconda,r
          show-channel-urls: true
          use-only-tar-bz2: true

      - name: Install Nextflow
        env:
          CAPSULE_LOG: none
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: Run pipeline with test data
        run: |
          conda clean --all -f
          nextflow run ${GITHUB_WORKSPACE} -profile test,conda
          
      - name: Run pipeline with no control data
        run: |
          nextflow run ${GITHUB_WORKSPACE} -profile test_no_input,conda